### ISSUE TITLE
Database Design and Models Explanation

### ISSUE THREAD

**Issue by Mdavid508** [Mdavid508/kwako#11]
You need to explain to us, how the database is working in terms of Registration,Login and the other functionalities such as booking and Payments

**Comment by kariuki-joseph** [comment]
## Database Design

![Image](https://user-images.githubusercontent.com/70845241/226090368-28a3b0f4-91a1-4c38-b0b4-20d2d632aaac.png)

Above is the database design.  

The models are not part of the database design but they are the associated java classes for the above design.  

In case of any clarifications or quiz, drop it in the comment section below.  

Thanks!

**Comment by Mdavid508** [comment]
So even while declaring the variables for use in our java files we use those data types associated with each variable right?
