### ISSUE TITLE
Missing activities & functionalities

### ISSUE THREAD

**Issue by asenawritescode** [Mdavid508/kwako#18]
### Check the design after the payments page. 
There is a **missing activity**.

![image](https://user-images.githubusercontent.com/67445192/228504912-e523abc4-c873-4201-97ba-0b2a44c47e1b.png)

Kindly set it up so that I can complete the Mpesa Functionality Task.

**Comment by asenawritescode** [comment]
### I need data to be passed on to the House Booking Page so that I can be able to complete my task.
- Change the total amount EditView to a TextView
- Pass the deposit and rent data to the page to complete the payment functionality.

Find attached the image to the activities mentioned 

![image](https://user-images.githubusercontent.com/67445192/228505411-f8cfc5af-368a-4956-8a2e-5d9d576c836f.png)
![image](https://user-images.githubusercontent.com/67445192/228505513-43a06d9a-d95a-4602-b5c6-e8bb20262d27.png)

**Comment by Mdavid508** [comment]
The missing activity ill be implemented by the end of the day

**Comment by kariuki-joseph** [comment]
> ### I need data to be passed on to the House Booking Page so that I can be able to complete my task.
> 
>     * Change the total amount EditView to a TextView
> 
>     * Pass the deposit and rent data to the page to complete the payment functionality.
> 
> 
> Find attached the image to the activities mentioned
> 
> ![image](https://user-images.githubusercontent.com/67445192/228505411-f8cfc5af-368a-4956-8a2e-5d9d576c836f.png) ![image](https://user-images.githubusercontent.com/67445192/228505513-43a06d9a-d95a-4602-b5c6-e8bb20262d27.png)

Noted. Working on this.
