### ISSUE TITLE
Failure of loading the booking page after one has clicked the book button

### ISSUE THREAD

**Issue by Mdavid508** [Mdavid508/kwako#19]
@kariuki-joseph I am not sure why after I have created a start activity that leads to the dialog in the booking page of the booking, the app is not able to move from that page to the booking page, instead it keeps logging out.
I have tried to investigate the issue in the logcat and havent been able to come up with a solution. I will push the code in my branch maybe you can have a look at it.

**Comment by kariuki-joseph** [comment]
Well noted.  Lemme pull and check

**Comment by kariuki-joseph** [comment]
Even before I check on the issue, this page I recommend you check on **AlertDialog** in android. It is better, since it is just like a modal in web, so you won't need to create a different activity for it. 

Check on that and implement using it instead.
